# Generated by Django 4.2 on 2023-05-13 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='2023-2024', max_length=100, null=True)),
                ('start_end_year', models.CharField(default='Academic Year of August 2023 - May 2024', max_length=100, null=True)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Class_Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(choices=[('August 2021- June 2022', 'August 2021- June 2022'), ('August 2022- June 2023', 'August 2022- June 2023'), ('August 2023- June 2024', 'August 2023- June 2024'), ('August 2024- June 2025', 'August 2024- June 2025')], default='---Please Select----', max_length=100, null=True)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'verbose_name_plural': 'Class_Academic',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('Grade 12A', 'Grade 12A'), ('Grade 12B', 'Grade 12B'), ('Grade 11A', 'Grade 11A'), ('Grade 11B', 'Grade 11B'), ('Grade 10A', 'Grade 10A'), ('Grade 10B', 'Grade 10B'), ('Grade 9A', 'Grade 9A'), ('Grade 9B', 'Grade 9B'), ('Grade 8A', 'Grade 8A'), ('Grade 8B', 'Grade 8B'), ('Grade 7A', 'Grade 7A'), ('Grade 7B', 'Grade 7B'), ('Grade 6A', 'Grade 6A'), ('Grade 6B', 'Grade 6B'), ('Grade 5A', 'Grade 5A'), ('Grade 5B', 'Grade 5B'), ('Grade 4A', 'Grade 4A'), ('Grade 4B', 'Grade 4B'), ('Grade 3A', 'Grade 3A'), ('Grade 3B', 'Grade 3B'), ('Grade 2A', 'Grade 2A'), ('Grade 2B', 'Grade 2B'), ('Grade 1A', 'Grade 1A'), ('Grade 1B', 'Grade 1B'), ('Grade KA', 'Grade KA'), ('Grade KB', 'Grade KB')], default='Grade 12A', max_length=100, null=True)),
                ('class_bld', models.CharField(choices=[('Main Bld.', 'Main Bld.'), ('Library Bld.', 'Library Bld.'), ('Picnic', 'Picinic'), ('12th Grade Bld.', '12th Grade Bld.')], default='Main Bld.', max_length=100, null=True)),
                ('class_capacity', models.CharField(choices=[('25', '25'), ('30', '30'), ('20', '20')], default='25', max_length=100, null=True)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Enroll_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, null=True)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='Entrance_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('Grade K-3', 'Grade K-3'), ('Grade 4-8', 'Grade 4-8'), ('Grade 9-12', 'Grade 9-12')], default='Grade k-3', max_length=100, null=True)),
                ('class_building', models.CharField(choices=[('Main Bld.', 'Main Bld.'), ('Library Bld.', 'Library Bld.'), ('Picnic', 'Picinic'), ('12th Grade Bld.', '12th Grade Bld.')], default='Main Bld.', max_length=100, null=True)),
                ('time_schedule', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], default='Morning', max_length=100, null=True)),
                ('date_exam', models.CharField(choices=[('12th of June', '12th of June'), ('13th of June', '13th of June'), ('14th of June', '14th of June'), ('15th of June', '15th of June')], default='13th of June', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True)),
                ('age', models.CharField(max_length=100)),
                ('DoB', models.DateField(null=True, verbose_name='date of birth')),
                ('birth_address', models.CharField(max_length=60, null=True)),
                ('nationality', models.CharField(choices=[('Cambodian', 'Cambodian'), ('Thai', 'Thai'), ('Asian', 'Asian'), ('Others', 'Others')], default='Cambodian', max_length=100, null=True)),
                ('religion', models.CharField(choices=[('SDA Christian', 'SDA Christian'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Buddhism', 'Buddhism')], default='--Select--', max_length=100, null=True)),
                ('apply_grade_level', models.CharField(choices=[('Grade 12', 'Grade 12'), ('Grade 11', 'Grade 11'), ('Grade 10', 'Grade 10'), ('Grade 9', 'Grade 9'), ('Grade 8', 'Grade 8'), ('Grade 7', 'Grade 7'), ('Grade 6', 'Grade 6'), ('Grade 5', 'Grade 5'), ('Grade 4', 'Grade 4'), ('Grade 3', 'Grade 3'), ('Grade 2', 'Grade 2'), ('Grade 1', 'Grade 1'), ('Grade K', 'Grade K')], default='--Select--', max_length=100, null=True)),
                ('academic_year', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='2022-2023', max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('health_record', models.CharField(choices=[('Heart problems', 'Heart problems'), ('High Blood Pressure', 'High Blood Pressure'), ('ADHD', 'ADHD'), ('Eating Disorder', 'Eating Disorder'), ('Medicine', 'Medicine'), ('Food Allergic', 'Food Allergic'), ('Injury', 'Injury'), ('Mental Health', 'Mental Health'), ('None', 'None'), ('Others', 'Others')], default='None', max_length=100, null=True)),
                ('physical_checkup', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100, null=True)),
                ('vaccinated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100, null=True)),
                ('dose_vaccination', models.CharField(choices=[('1st Dose', '1st Dose'), ('2nd Dose', '2nd Dose'), ('3rd Dose', '3rd Dose'), ('4th Dose', '4th Dose'), ('5th Dose', '5h Dose'), ('6th Dose', '6th Dose')], default='Yes', max_length=100, null=True)),
                ('id_vaccine_card', models.CharField(max_length=60, null=True)),
                ('early_school', models.CharField(default='School Name', max_length=100, null=True)),
                ('parent_name', models.CharField(max_length=60, null=True)),
                ('parent_occupation', models.CharField(max_length=60, null=True)),
                ('parent_email', models.CharField(max_length=60, null=True)),
                ('parent_contact', models.CharField(default='+855 ', max_length=60, null=True)),
                ('emergency_cont_name', models.CharField(max_length=60, null=True)),
                ('emergency_contact', models.CharField(default='+855 ', max_length=60, null=True)),
                ('emergency_address', models.CharField(max_length=60, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('country', models.CharField(max_length=60, null=True)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='Registree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True)),
                ('DoB', models.DateField(null=True, verbose_name='date of birth')),
                ('nationality', models.CharField(choices=[('Cambodian', 'Cambodian'), ('Thai', 'Thai'), ('Asian', 'Asian'), ('Others', 'Others')], default='Cambodian', max_length=100, null=True)),
                ('religion', models.CharField(choices=[('SDA Christian', 'SDA Christian'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Buddhism', 'Buddhism')], default='SDA Christian', max_length=100, null=True)),
                ('grade_level', models.CharField(choices=[('Grade 12', 'Grade 12'), ('Grade 11', 'Grade 11'), ('Grade 10', 'Grade 10'), ('Grade 9', 'Grade 9'), ('Grade 8', 'Grade 8'), ('Grade 7', 'Grade 7'), ('Grade 6', 'Grade 6'), ('Grade 5', 'Grade 5'), ('Grade 4', 'Grade 4'), ('Grade 3', 'Grade 3'), ('Grade 2', 'Grade 2'), ('Grade 1', 'Grade 1'), ('Grade K', 'Grade K')], default='Grade 8', max_length=100, null=True)),
                ('academic_year', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='2022-2023', max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('parent_name', models.CharField(max_length=60, null=True)),
                ('parent_occupation', models.CharField(max_length=60, null=True)),
                ('parent_email', models.CharField(max_length=60, null=True)),
                ('parent_contact', models.CharField(default='+855 ', max_length=60, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('country', models.CharField(max_length=60, null=True)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=60, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True)),
                ('contact', models.CharField(default='+855 ', max_length=60, null=True)),
                ('position', models.CharField(choices=[('Principal', 'Principal'), ('Vice-Principal', 'Vice-Principal'), ('HR', 'HR'), ('Janitor', 'Janitor'), ('Guard', 'Guard'), ('Maintenance', 'Maintenance'), ('Homeroom Teacher', 'Homeroom Teacher'), ('Subject Teacher', 'Subject Teacher'), ('Teacher Assistant', 'Teacher Assistant'), ('Librarian', 'Librarian'), ('Registrar', 'Registrar'), ('Accountant', 'Accountant')], max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(choices=[('Grade 12A', 'Grade 12A'), ('Grade 12B', 'Grade 12B'), ('Grade 11A', 'Grade 11A'), ('Grade 11B', 'Grade 11B'), ('Grade 10A', 'Grade 10A'), ('Grade 10B', 'Grade 10B'), ('Grade 9A', 'Grade 9A'), ('Grade 9B', 'Grade 9B'), ('Grade 8A', 'Grade 8A'), ('Grade 8B', 'Grade 8B'), ('Grade 7A', 'Grade 7A'), ('Grade 7B', 'Grade 7B'), ('Grade 6A', 'Grade 6A'), ('Grade 6B', 'Grade 6B'), ('Grade 5A', 'Grade 5A'), ('Grade 5B', 'Grade 5B'), ('Grade 4A', 'Grade 4A'), ('Grade 4B', 'Grade 4B'), ('Grade 3A', 'Grade 3A'), ('Grade 3B', 'Grade 3B'), ('Grade 2A', 'Grade 2A'), ('Grade 2B', 'Grade 2B'), ('Grade 1A', 'Grade 1A'), ('Grade 1B', 'Grade 1B'), ('Grade KA', 'Grade KA'), ('Grade KB', 'Grade KB')], default='Grade 7', max_length=100, null=True)),
                ('class_subject', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Computer'), ('B', 'Computer Literacy'), ('C', 'Computer Keyboarding'), ('D', 'Yearbook'), ('E', 'Art Appreciation'), ('F', 'Music'), ('G', 'Music Appreciation'), ('H', 'Arts'), ('I', 'Art Appreciation'), ('J', 'P.E.'), ('K', 'Drama'), ('L', 'Library'), ('M', 'Science'), ('N', 'Homelife'), ('O', 'Physical Science'), ('P', 'Biology'), ('Q', 'Physic'), ('R', 'Chemistry'), ('S', 'Mathematic'), ('T', 'Pre-Algebra'), ('U', 'Algebra I'), ('V', 'Algebra II'), ('W', 'Pre-Calculus'), ('X', 'Social Studies'), ('Y', 'World History'), ('Z', 'Ancient History'), ('AA', 'Morality'), ('AB', 'Pathfinder'), ('AC', 'Chapel'), ('AD', 'Khmer'), ('AE', 'Khmer Geography'), ('AF', 'Khmer Literacy'), ('AG', 'Reading/Handwriting'), ('AH', 'English/Spelling'), ('AI', 'English I'), ('AJ', 'English II'), ('AK', 'English IIII')], default='A', max_length=300, null=True)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, null=True)),
                ('last_name', models.CharField(max_length=60, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True)),
                ('DoB', models.DateField(null=True, verbose_name='date of birth')),
                ('nationality', models.CharField(choices=[('Thai', 'Thai'), ('Asian', 'Asian'), ('Others', 'Others'), ('Cambodian', 'Cambodian'), ('Phillipines', 'Phillipines')], default='Cambodian', max_length=100, null=True)),
                ('religion', models.CharField(choices=[('SDA Christian', 'SDA Christian'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Buddhism', 'Buddhism')], default='SDA Christian', max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bachelor_degree', models.CharField(choices=[('BS of IT', 'BS of IT'), ('BA of TESOL', 'BA of TESOL'), ('BS of Science', 'BS of Science'), ('BA of Theology', 'BA of Theology'), ('MBA of Theology', 'MBA of Theology'), ('BA of Education', 'BA of Education'), ('MBA of Education', 'MBA of Education'), ('MBA of Administration', 'MBA of Administration')], default='BA of Science', max_length=100, null=True)),
                ('email', models.CharField(default=' @caisedu.com', max_length=60, null=True)),
                ('phone_num', models.CharField(default='+855 ', max_length=60, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('country', models.CharField(choices=[('Cambodia', 'Cambodia'), ('Others', 'Others')], default='Cambodia', max_length=100, null=True)),
                ('date_joined', models.DateField(null=True, verbose_name='date joined')),
                ('staff_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='caisam.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True)),
                ('grade_level', models.CharField(choices=[('Grade 12', 'Grade 12'), ('Grade 11', 'Grade 11'), ('Grade 10', 'Grade 10'), ('Grade 9', 'Grade 9'), ('Grade 8', 'Grade 8'), ('Grade 7', 'Grade 7'), ('Grade 6', 'Grade 6'), ('Grade 5', 'Grade 5'), ('Grade 4', 'Grade 4'), ('Grade 3', 'Grade 3'), ('Grade 2', 'Grade 2'), ('Grade 1', 'Grade 1'), ('Grade K', 'Grade K')], default='Grade 5', max_length=100, null=True)),
                ('student_status', models.CharField(choices=[('New Student', 'New Student'), ('Existing Student', 'Exisiting Student')], default='New Student', max_length=100, null=True)),
                ('age', models.CharField(max_length=100)),
                ('DoB', models.DateField(default='YYYY-MM-DD', null=True, verbose_name='date of birth')),
                ('nationality', models.CharField(choices=[('Thai', 'Thai'), ('Asian', 'Asian'), ('Others', 'Others'), ('Cambodian', 'Cambodian'), ('Phillipines', 'Phillipines')], default='Cambodian', max_length=100, null=True)),
                ('religion', models.CharField(choices=[('SDA Christian', 'SDA Christian'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Buddhism', 'Buddhism')], default='SDA Christian', max_length=100, null=True)),
                ('student_idcard', models.CharField(default='201600...', max_length=60)),
                ('email', models.CharField(default=' @caisedu.com', max_length=60, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('father_status', models.CharField(choices=[('Living', 'Living'), ('Deceased', 'Deceased')], default='Living', max_length=100, null=True)),
                ('father_firstname', models.CharField(max_length=60, null=True)),
                ('father_lastname', models.CharField(max_length=60, null=True)),
                ('father_occupation', models.CharField(max_length=60, null=True)),
                ('mother_status', models.CharField(choices=[('Living', 'Living'), ('Deceased', 'Deceased')], default='Living', max_length=100, null=True)),
                ('mother_firstname', models.CharField(max_length=60, null=True)),
                ('mother_lastname', models.CharField(max_length=60, null=True)),
                ('mother_occupation', models.CharField(max_length=60, null=True)),
                ('parent_email', models.CharField(max_length=60, null=True)),
                ('parent_contact1', models.CharField(default='+855 ', max_length=60, null=True)),
                ('parent_contact2', models.CharField(default='+855 ', max_length=60, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('country', models.CharField(choices=[('Cambodia', 'Cambodia'), ('Others', 'Others')], default='Cambodia', max_length=100, null=True)),
                ('date_joined', models.DateField(null=True, verbose_name='date joined')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caisam.city')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caisam.country')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Staff_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs_id_fk', to='caisam.staff')),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('IELTS', 'IELTS'), ('WIDA', 'WIDA'), ('MAP TEST', 'MAP TEST')], default='WIDA', max_length=100, null=True)),
                ('exam_status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='PASS', max_length=100, null=True)),
                ('exam_score', models.CharField(default='%', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('exam_card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='caisam.enroll_exam')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll_NStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('Enrollment Approved', 'Enrollment Approved'), ('Enrollment Rejected', 'Enrollment Rejected'), ('IN PROBATION', 'IN PROBATION')], default='Enrollment Approved', max_length=100, null=True)),
                ('student_status', models.CharField(choices=[('New Student', 'New Student'), ('Existing Student', 'Existing Student')], default='New Student', max_length=100, null=True)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_year_id_fk', to='caisam.academic_year')),
                ('examid_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_id_fk', to='caisam.exam_stats')),
                ('into_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_level_id_fk', to='caisam.classroom')),
                ('student_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'New Student Enrollment',
            },
        ),
        migrations.AddField(
            model_name='enroll_exam',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_exam_id_fk', to='caisam.entrance_exam'),
        ),
        migrations.AddField(
            model_name='enroll_exam',
            name='prospect_name',
            field=models.ForeignKey(default='202200220', on_delete=django.db.models.deletion.CASCADE, related_name='prospect_id_fk', to='caisam.prospect'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisam.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_id_fk', to='caisam.subject'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caisam.state'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisam.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisam.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisam.state')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisam.street')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
