# Generated by Django 4.2 on 2023-05-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caisam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_academic',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='enroll_nstudent',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='enroll_nstudent',
            name='student_status',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='age',
        ),
        migrations.AddField(
            model_name='class_academic',
            name='class_academic',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, related_name='class_academic_id_fk', to='caisam.enroll_nstudent'),
        ),
        migrations.AddField(
            model_name='class_academic',
            name='class_name',
            field=models.CharField(default='01', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_academic',
            name='student_class',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, related_name='student_id_fk', to='caisam.student'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_teacher_id_fk', to='caisam.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
