# Generated by Django 4.2 on 2023-05-14 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caisam', '0002_remove_class_academic_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_academic',
            name='class_academic',
            field=models.ForeignKey(default='Grade 12', on_delete=django.db.models.deletion.CASCADE, related_name='class_academic_id_fk', to='caisam.classroom'),
        ),
    ]
